package freebsd

const (
	UMTX_OP_LOCK = 0	/* COMPAT10 */
	UMTX_OP_UNLOCK = 1	/* COMPAT10 */
	UMTX_OP_WAIT = 2
	UMTX_OP_WAKE = 3
	UMTX_OP_MUTEX_TRYLOCK = 4
	UMTX_OP_MUTEX_LOCK = 5
	UMTX_OP_MUTEX_UNLOCK = 6
	UMTX_OP_SET_CEILING = 7
	UMTX_OP_CV_WAIT = 8
	UMTX_OP_CV_SIGNAL = 9
	UMTX_OP_CV_BROADCAST = 10
	UMTX_OP_WAIT_UINT = 11
	UMTX_OP_RW_RDLOCK = 12
	UMTX_OP_RW_WRLOCK = 13
	UMTX_OP_RW_UNLOCK = 14
	UMTX_OP_WAIT_UINT_PRIVATE = 15
	UMTX_OP_WAKE_PRIVATE = 16
	UMTX_OP_MUTEX_WAIT = 17
	UMTX_OP_MUTEX_WAKE = 18	/* deprecated */
	UMTX_OP_SEM_WAIT = 19	/* deprecated */
	UMTX_OP_SEM_WAKE = 20	/* deprecated */
	UMTX_OP_NWAKE_PRIVATE = 21
	UMTX_OP_MUTEX_WAKE2 = 22
	UMTX_OP_SEM2_WAIT = 23
	UMTX_OP_SEM2_WAKE = 24
	UMTX_OP_SHM = 25
	UMTX_OP_ROBUST_LISTS = 26
	UMTX_OP_GET_MIN_TIMEOUT = 27
	UMTX_OP_SET_MIN_TIMEOUT = 28
)
